/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    'abstract-statuses': AbstractStatus;
    abstracts: Abstract;
    appendices: Appendix;
    'agenda-items': AgendaItem;
    'conference-days': ConferenceDay;
    'conference-notices': ConferenceNotice;
    conferences: Conference;
    countries: Country;
    institutions: Institution;
    'italian-regions': ItalianRegion;
    people: Person;
    'programme-push-subscriptions': ProgrammePushSubscription;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    media: {
      abstract: 'abstracts';
      taggedPeople: 'people';
    };
    'agenda-items': {
      children: 'agenda-items';
      childAbstracts: 'abstracts';
    };
    'conference-days': {
      agendaItems: 'agenda-items';
    };
    conferences: {
      days: 'conference-days';
      abstracts: 'abstracts';
      appendices: 'appendices';
      notices: 'conference-notices';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'abstract-statuses': AbstractStatusesSelect<false> | AbstractStatusesSelect<true>;
    abstracts: AbstractsSelect<false> | AbstractsSelect<true>;
    appendices: AppendicesSelect<false> | AppendicesSelect<true>;
    'agenda-items': AgendaItemsSelect<false> | AgendaItemsSelect<true>;
    'conference-days': ConferenceDaysSelect<false> | ConferenceDaysSelect<true>;
    'conference-notices': ConferenceNoticesSelect<false> | ConferenceNoticesSelect<true>;
    conferences: ConferencesSelect<false> | ConferencesSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    institutions: InstitutionsSelect<false> | InstitutionsSelect<true>;
    'italian-regions': ItalianRegionsSelect<false> | ItalianRegionsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    'programme-push-subscriptions': ProgrammePushSubscriptionsSelect<false> | ProgrammePushSubscriptionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    footer: Footer;
    'active-conference': ActiveConference;
    'conference-archive': ConferenceArchive;
    'programme-alerts': ProgrammeAlert;
  };
  globalsSelect: {
    footer: FooterSelect<false> | FooterSelect<true>;
    'active-conference': ActiveConferenceSelect<false> | ActiveConferenceSelect<true>;
    'conference-archive': ConferenceArchiveSelect<false> | ConferenceArchiveSelect<true>;
    'programme-alerts': ProgrammeAlertsSelect<false> | ProgrammeAlertsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Abstracts that use this image. Change the link from the abstract, not from here.
   */
  abstract?: {
    docs?: (number | Abstract)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * People whose profile photo is this file. Change the photo on the person.
   */
  taggedPeople?: {
    docs?: (number | Person)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Scientific abstracts for an edition. Best created and ordered from the conference Abstract tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abstracts".
 */
export interface Abstract {
  id: number;
  _abstracts_abstracts_order?: string | null;
  _abstracts_childAbstracts_order?: string | null;
  _order?: string | null;
  title: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Research or session code (e.g. “CF crio”). Does not have to be unique.
   */
  code?: string | null;
  /**
   * If selected and Content is empty, the default sections for this Status are created.
   */
  status?: (number | null) | AbstractStatus;
  /**
   * Other Code/Status pairs. Each row adds an appendix after the main one (same order).
   */
  relatedCodes?:
    | {
        code?: string | null;
        status?: (number | null) | AbstractStatus;
        id?: string | null;
      }[]
    | null;
  /**
   * Structured sections. Defaults are created when you select Status and this list is empty.
   */
  content?:
    | {
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The first row is the appendix for the main Code/Status; the following follow Related codes. The row count stays 1 + Related codes.
   */
  appendices?:
    | {
        title?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Authors and speakers in order (same list). Drag rows; assign a Role and tick Speaker. Each person can appear only once.
   */
  authors?:
    | {
        person: number | Person;
        role: 'primaryInvestigator' | 'partner' | 'collaborator' | 'teamMember';
        isSpeaker?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ordered photos for this abstract (images only). On the site they appear first in the carousel, then Speaker photos (Team Member excluded). Media folder “Abstract pictures”.
   */
  picture?:
    | {
        image: number | Media;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Edition this abstract belongs to. Set automatically if you create it from the conference.
   */
  conference: number | Conference;
  /**
   * Sessions (Agenda items) of this edition. The same abstract can sit under more than one session.
   */
  agendaItems?: (number | AgendaItem)[] | null;
  /**
   * Plain-text Title derived from Title (lists).
   */
  plainTitle?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Abstract workflow statuses. Seeded; change only if you need different labels or colours.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abstract-statuses".
 */
export interface AbstractStatus {
  id: number;
  _order?: string | null;
  /**
   * Status key (e.g. new, ongoing, concluded).
   */
  status: string;
  /**
   * Section titles copied onto the abstract when you select this Status and Content is empty. Leave empty to copy nothing.
   */
  defaultContent?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Researchers, authors, speakers, and reviewers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  _order?: string | null;
  firstName: string;
  lastName: string;
  institution?: (number | null) | Institution;
  /**
   * Optional profile photo. Media folder “People photos”.
   */
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Generated from First name and Last name.
   */
  fullName?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Research institutes and labs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions".
 */
export interface Institution {
  id: number;
  _order?: string | null;
  name: string;
  country: number | Country;
  /**
   * Available only when Country is Italy.
   */
  region?: (number | null) | ItalianRegion;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * World countries for institutions. Reference data (seeded).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Italian regions for institution addresses. Reference data (seeded).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "italian-regions".
 */
export interface ItalianRegion {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Conference editions. Open an edition to manage days, abstracts, and the appendix.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conferences".
 */
export interface Conference {
  id: number;
  /**
   * Formatted conference name. Title and slug are derived from this text.
   */
  name: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Edition year. Several editions in the same year are allowed.
   */
  year: number;
  /**
   * Used in the header and as the browser tab icon. Media folder “Conference logos”.
   */
  logo?: (number | null) | Media;
  /**
   * Buttons, links, and section accents. Adapts automatically to light and dark theme.
   */
  primaryColor: string;
  /**
   * Keynotes, badges, and secondary highlights. Adapts automatically to light and dark theme.
   */
  secondaryColor: string;
  /**
   * Add Content (one or more text columns with a Width, as in the Payload Pages template), accordion, callout, buttons, quotes, and separators. Blocks other than Content also have a Width. Widths add up on a 12-column row from the large breakpoint up (Full = 12, Two thirds = 8, Half = 6, One third = 4) and wrap. On small screens everything is full width and stacks in order.
   */
  intro?:
    | (
        | IntroContentBlock
        | IntroAccordionBlock
        | IntroCalloutBlock
        | IntroCtaBlock
        | IntroQuoteBlock
        | IntroSeparatorBlock
      )[]
    | null;
  /**
   * Sorted by date (soonest first). One day per calendar date.
   */
  days?: {
    docs?: (number | ConferenceDay)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Scientific abstracts for this edition. Link them to sessions from the abstract or from the session.
   */
  abstracts?: {
    docs?: (number | Abstract)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * At most one appendix per conference. Open it to add blocks and drag them to reorder.
   */
  appendices?: {
    docs?: (number | Appendix)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Short plain-text notices. Drag to set banner order. Create a new notice for each push: it cannot be sent again.
   */
  notices?: {
    docs?: (number | ConferenceNotice)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  city: string;
  country: string;
  address: string;
  /**
   * X coordinate (e.g. 13.8046 for Trieste).
   */
  longitude?: number | null;
  /**
   * Y coordinate (e.g. 45.6495 for Trieste).
   */
  latitude?: number | null;
  /**
   * Optional details (room, entrance, accessibility).
   */
  location?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * This block is the short card people see before opening the page: the blue title on Google, the preview on WhatsApp or LinkedIn, and the browser tab text. It is not the page content (that lives in Name, Intro, and Venue).
   */
  meta?: {
    /**
     * The title Google and similar engines usually show. Write the edition name as someone would search for it, with the year if needed (example: “FCR 2026 — Trieste”). Stay around 60 characters so it is not cut. Use Generate to copy the conference name, then shorten it if needed. If you leave it empty, the public page uses the conference name plus “FCR”.
     */
    title?: string | null;
    /**
     * The image that appears when someone shares this edition’s link (WhatsApp, Slack, LinkedIn, email). Prefer a wide landscape photo of the venue, poster, or logo on a simple background. Aim under 500 KB; the upload limit is 12 MB. A 1200×630 px image fills the preview without cropping the subject. If you leave it empty, the site uses the default FCR share image.
     */
    image?: (number | null) | Media;
    /**
     * Two sentences (about 150–160 characters) under the title on Google and in the share preview. Say which edition it is, where it is held, and who it is for. Example: “FCR 2026 is a regenerative medicine meeting in Trieste for clinicians and researchers. Dates, venue, and programme.” Do not paste keyword lists. If you leave it empty, search engines reconstruct the text from the page.
     */
    description?: string | null;
  };
  /**
   * Optional. ChatGPT, Gemini, Perplexity, and similar tools often cite short stable facts, not long page copy. Fill these so they can name the edition correctly. They are not shown as FAQs on the site. Dates, city, address, and coordinates come from Days and Venue: do not repeat them here unless you need a precise one-line wording.
   */
  geo?: {
    /**
     * One or two factual sentences an assistant can quote. Start with the official name, then place, audience, and topic. Example: “FCR 2026 is the annual FCR regenerative medicine meeting in Trieste for clinicians and researchers.” Avoid slogans. If empty, assistants use the short listing text above, then the page content.
     */
    summary?: string | null;
    /**
     * The exact name you want cited as the subject of the page, so it is not confused with another year or FCR event. Example: “FCR 2026” or “Fondazione conferenza 2026, Trieste”. Keep it short. If empty, the conference name is used.
     */
    primaryEntity?: string | null;
    /**
     * Short label–value pairs to quote as-is. Use them for things that are easy to get wrong (topic, audience, language, organised by). Do not duplicate city, address, or dates unless you need a precise sentence. Examples: Topic → Regenerative medicine; Audience → Clinicians and researchers; Language → English. Four to eight facts are enough.
     */
    keyFacts?:
      | {
          /**
           * The kind of fact, in one or two words. Examples: Topic, Audience, Language, Organised by.
           */
          label?: string | null;
          /**
           * The fact, as you would tell a colleague. One line. Example: “Clinicians and academic researchers”.
           */
          value?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Plain-text Title derived from Name (lists, slug, and public listing).
   */
  title?: string | null;
  /**
   * First time this edition went live. Stays stable for SEO; these are not the event dates (those live in Days).
   */
  publishedAt?: string | null;
  publicArchive?: boolean | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroContentBlock".
 */
export interface IntroContentBlock {
  /**
   * Widths add up on a 12-column row from the large breakpoint up (Full = 12, Two thirds = 8, Half = 6, One third = 4) and wrap. On small screens each column is full width.
   */
  columns?:
    | {
        size: 'full' | 'twoThirds' | 'half' | 'oneThird';
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroAccordionBlock".
 */
export interface IntroAccordionBlock {
  size: 'full' | 'twoThirds' | 'half' | 'oneThird';
  items?:
    | {
        title: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        defaultOpen?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroCalloutBlock".
 */
export interface IntroCalloutBlock {
  size: 'full' | 'twoThirds' | 'half' | 'oneThird';
  /**
   * Use Deadline for dates and deadlines, Important for notices to read.
   */
  tone: 'note' | 'important' | 'deadline';
  title?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroCtaBlock".
 */
export interface IntroCtaBlock {
  size: 'full' | 'twoThirds' | 'half' | 'oneThird';
  label: string;
  destination: 'programme' | 'venue' | 'appendix' | 'custom';
  /**
   * External site, or a page path such as /archive/…
   */
  url?: string | null;
  newTab?: boolean | null;
  appearance: 'solid' | 'outline';
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroQuoteBlock".
 */
export interface IntroQuoteBlock {
  size: 'full' | 'twoThirds' | 'half' | 'oneThird';
  quote: string;
  /**
   * Speaker, role, or source, optional.
   */
  attribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroSeparatorBlock".
 */
export interface IntroSeparatorBlock {
  size: 'full' | 'twoThirds' | 'half' | 'oneThird';
  style: 'line' | 'space';
  id?: string | null;
  blockName?: string | null;
  blockType: 'separator';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conference-days".
 */
export interface ConferenceDay {
  id: number;
  date: string;
  startTime: string;
  /**
   * Can be earlier than Start time if the day crosses midnight.
   */
  endTime: string;
  /**
   * Top-level sessions of this day. Nested items are managed on the parent. Drag to reorder.
   */
  agendaItems?: {
    docs?: (number | AgendaItem)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Owning conference. Set automatically if you create the day from the conference.
   */
  conference: number | Conference;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agenda-items".
 */
export interface AgendaItem {
  id: number;
  '_agenda-items_agendaItems_order'?: string | null;
  '_agenda-items_children_order'?: string | null;
  _order?: string | null;
  /**
   * Formatted session title. Plain Title is derived from this.
   */
  name: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Select the day first. Start time and End time stay within that day’s hours.
   */
  day: number | ConferenceDay;
  /**
   * Required. On items without child sessions (talks) this drives “My programme” reminders. Must fall within the day’s window.
   */
  startTime?: string | null;
  /**
   * Required. Defines the end of the “Live” window. Must fall within the day’s hours.
   */
  endTime?: string | null;
  /**
   * Highlights this session on the site.
   */
  isKeynote?: boolean | null;
  durationMinutes?: number | null;
  /**
   * Optional Lucide icon. Search filters the list; scroll to see them all.
   */
  icon: {
    provider: string;
    name?: string | null;
  };
  /**
   * Optional notes or details about the session.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Talks or nested sessions. Drag to order them inside this item.
   */
  children?: {
    docs?: (number | AgendaItem)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Scientific abstracts under this session. The same abstract can also appear on other items.
   */
  childAbstracts?: {
    docs?: (number | Abstract)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Plain-text Title derived from Title (lists).
   */
  title?: string | null;
  /**
   * Optional parent item (same day). Leave empty for top-level sessions.
   */
  parent?: (number | null) | AgendaItem;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * One appendix per edition. Add ordered blocks (text, institution list, …) and drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appendices".
 */
export interface Appendix {
  id: number;
  /**
   * Each block needs a Title (tab label). Basic text uses the same Content columns, accordion, and layout as the intro. Drag to reorder tabs.
   */
  blocks: (
    BasicTextAppendixBlock | ReviewersAppendixBlock | ResearchProjectsAppendixBlock | InstitutionsAppendixBlock
  )[];
  /**
   * Edition this appendix belongs to. Each conference can have only one.
   */
  conference: number | Conference;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BasicTextAppendixBlock".
 */
export interface BasicTextAppendixBlock {
  /**
   * Tab label in the public appendix.
   */
  title: string;
  /**
   * Shown next to the tab title. If empty, a default icon for this block type is used.
   */
  icon: {
    provider: string;
    name?: string | null;
  };
  /**
   * Add Content (one or more text columns with a Width, as in the Payload Pages template), accordion, callout, buttons, quotes, and separators. Blocks other than Content also have a Width. Widths add up on a 12-column row from the large breakpoint up (Full = 12, Two thirds = 8, Half = 6, One third = 4) and wrap. On small screens everything is full width and stacks in order.
   */
  layout?:
    | (
        | IntroContentBlock
        | IntroAccordionBlock
        | IntroCalloutBlock
        | IntroCtaBlock
        | IntroQuoteBlock
        | IntroSeparatorBlock
      )[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'basicText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewersAppendixBlock".
 */
export interface ReviewersAppendixBlock {
  title: string;
  /**
   * Shown next to the tab title. If empty, a default icon for this block type is used.
   */
  icon: {
    provider: string;
    name?: string | null;
  };
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'reviewers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResearchProjectsAppendixBlock".
 */
export interface ResearchProjectsAppendixBlock {
  title: string;
  /**
   * Shown next to the tab title. If empty, a default icon for this block type is used.
   */
  icon: {
    provider: string;
    name?: string | null;
  };
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'researchProjects';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InstitutionsAppendixBlock".
 */
export interface InstitutionsAppendixBlock {
  title: string;
  /**
   * Shown next to the tab title. If empty, a default icon for this block type is used.
   */
  icon: {
    provider: string;
    name?: string | null;
  };
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * All institutions except those of non–team-member authors on this conference’s abstracts. Create new ones here if needed. Drag to set display order.
   */
  institutions?: (number | Institution)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'institutions';
}
/**
 * Live programme changes. Edit them from the conference Notices tab. Use Send push for lock-screen notifications.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conference-notices".
 */
export interface ConferenceNotice {
  id: number;
  '_conference-notices_notices_order'?: string | null;
  _order?: string | null;
  /**
   * Short title for the banner and lock screen (max 40 characters).
   */
  title: string;
  /**
   * Plain text only (max 120 characters). Appears on the site banner and in the push.
   */
  body: string;
  /**
   * Banner colour. Prefer Change for room or time changes.
   */
  severity: 'info' | 'change' | 'urgent';
  /**
   * If on, visitors see the notice on the edition’s public page.
   */
  showOnSite?: boolean | null;
  /**
   * If on, Send push delivers a lock-screen notification to subscribed devices of this edition.
   */
  sendPush?: boolean | null;
  /**
   * Optional. The push goes to people who saved this item, a talk inside it, or a linked abstract, plus people subscribed to conference updates. The banner stays visible to everyone.
   */
  relatedAgendaItem?: (number | null) | AgendaItem;
  /**
   * Optional path on this site, e.g. #programme or ?agenda=123. Empty opens the edition home (or the linked session, if set).
   */
  linkPath?: string | null;
  /**
   * Optional. Banner hidden before this time.
   */
  startsAt?: string | null;
  /**
   * Optional. Banner hidden after this time.
   */
  expiresAt?: string | null;
  /**
   * Filled automatically after a successful push send.
   */
  sentAt?: string | null;
  /**
   * Devices that received the last send.
   */
  pushSent?: number | null;
  /**
   * Expired or missing push endpoints, cleaned on the last send.
   */
  pushRemoved?: number | null;
  /**
   * Edition this notice belongs to.
   */
  conference: number | Conference;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Browser push endpoints for My programme alerts. Do not edit them here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programme-push-subscriptions".
 */
export interface ProgrammePushSubscription {
  id: number;
  endpoint: string;
  p256dh: string;
  auth: string;
  conference: number;
  canonicalPath?: string | null;
  items:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * If true, this endpoint also receives editorial notices (room/time), not only session reminders.
   */
  conferenceUpdates?: boolean | null;
  notifiedSoon?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notifiedLive?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'abstract-statuses';
        value: number | AbstractStatus;
      } | null)
    | ({
        relationTo: 'abstracts';
        value: number | Abstract;
      } | null)
    | ({
        relationTo: 'appendices';
        value: number | Appendix;
      } | null)
    | ({
        relationTo: 'agenda-items';
        value: number | AgendaItem;
      } | null)
    | ({
        relationTo: 'conference-days';
        value: number | ConferenceDay;
      } | null)
    | ({
        relationTo: 'conference-notices';
        value: number | ConferenceNotice;
      } | null)
    | ({
        relationTo: 'conferences';
        value: number | Conference;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'institutions';
        value: number | Institution;
      } | null)
    | ({
        relationTo: 'italian-regions';
        value: number | ItalianRegion;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'programme-push-subscriptions';
        value: number | ProgrammePushSubscription;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  abstract?: T;
  taggedPeople?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abstract-statuses_select".
 */
export interface AbstractStatusesSelect<T extends boolean = true> {
  _order?: T;
  status?: T;
  defaultContent?:
    | T
    | {
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abstracts_select".
 */
export interface AbstractsSelect<T extends boolean = true> {
  _abstracts_abstracts_order?: T;
  _abstracts_childAbstracts_order?: T;
  _order?: T;
  title?: T;
  code?: T;
  status?: T;
  relatedCodes?:
    | T
    | {
        code?: T;
        status?: T;
        id?: T;
      };
  content?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  appendices?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  authors?:
    | T
    | {
        person?: T;
        role?: T;
        isSpeaker?: T;
        id?: T;
      };
  picture?:
    | T
    | {
        image?: T;
        description?: T;
        id?: T;
      };
  conference?: T;
  agendaItems?: T;
  plainTitle?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appendices_select".
 */
export interface AppendicesSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        basicText?: T | BasicTextAppendixBlockSelect<T>;
        reviewers?: T | ReviewersAppendixBlockSelect<T>;
        researchProjects?: T | ResearchProjectsAppendixBlockSelect<T>;
        institutions?: T | InstitutionsAppendixBlockSelect<T>;
      };
  conference?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BasicTextAppendixBlock_select".
 */
export interface BasicTextAppendixBlockSelect<T extends boolean = true> {
  title?: T;
  icon?:
    | T
    | {
        provider?: T;
        name?: T;
      };
  layout?:
    | T
    | {
        content?: T | IntroContentBlockSelect<T>;
        accordion?: T | IntroAccordionBlockSelect<T>;
        callout?: T | IntroCalloutBlockSelect<T>;
        cta?: T | IntroCtaBlockSelect<T>;
        quote?: T | IntroQuoteBlockSelect<T>;
        separator?: T | IntroSeparatorBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroContentBlock_select".
 */
export interface IntroContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        content?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroAccordionBlock_select".
 */
export interface IntroAccordionBlockSelect<T extends boolean = true> {
  size?: T;
  items?:
    | T
    | {
        title?: T;
        content?: T;
        defaultOpen?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroCalloutBlock_select".
 */
export interface IntroCalloutBlockSelect<T extends boolean = true> {
  size?: T;
  tone?: T;
  title?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroCtaBlock_select".
 */
export interface IntroCtaBlockSelect<T extends boolean = true> {
  size?: T;
  label?: T;
  destination?: T;
  url?: T;
  newTab?: T;
  appearance?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroQuoteBlock_select".
 */
export interface IntroQuoteBlockSelect<T extends boolean = true> {
  size?: T;
  quote?: T;
  attribution?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroSeparatorBlock_select".
 */
export interface IntroSeparatorBlockSelect<T extends boolean = true> {
  size?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewersAppendixBlock_select".
 */
export interface ReviewersAppendixBlockSelect<T extends boolean = true> {
  title?: T;
  icon?:
    | T
    | {
        provider?: T;
        name?: T;
      };
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResearchProjectsAppendixBlock_select".
 */
export interface ResearchProjectsAppendixBlockSelect<T extends boolean = true> {
  title?: T;
  icon?:
    | T
    | {
        provider?: T;
        name?: T;
      };
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InstitutionsAppendixBlock_select".
 */
export interface InstitutionsAppendixBlockSelect<T extends boolean = true> {
  title?: T;
  icon?:
    | T
    | {
        provider?: T;
        name?: T;
      };
  description?: T;
  institutions?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agenda-items_select".
 */
export interface AgendaItemsSelect<T extends boolean = true> {
  '_agenda-items_agendaItems_order'?: T;
  '_agenda-items_children_order'?: T;
  _order?: T;
  name?: T;
  day?: T;
  startTime?: T;
  endTime?: T;
  isKeynote?: T;
  durationMinutes?: T;
  icon?:
    | T
    | {
        provider?: T;
        name?: T;
      };
  description?: T;
  children?: T;
  childAbstracts?: T;
  title?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conference-days_select".
 */
export interface ConferenceDaysSelect<T extends boolean = true> {
  date?: T;
  startTime?: T;
  endTime?: T;
  agendaItems?: T;
  conference?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conference-notices_select".
 */
export interface ConferenceNoticesSelect<T extends boolean = true> {
  '_conference-notices_notices_order'?: T;
  _order?: T;
  title?: T;
  body?: T;
  severity?: T;
  showOnSite?: T;
  sendPush?: T;
  relatedAgendaItem?: T;
  linkPath?: T;
  startsAt?: T;
  expiresAt?: T;
  sentAt?: T;
  pushSent?: T;
  pushRemoved?: T;
  conference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conferences_select".
 */
export interface ConferencesSelect<T extends boolean = true> {
  name?: T;
  year?: T;
  logo?: T;
  primaryColor?: T;
  secondaryColor?: T;
  intro?:
    | T
    | {
        content?: T | IntroContentBlockSelect<T>;
        accordion?: T | IntroAccordionBlockSelect<T>;
        callout?: T | IntroCalloutBlockSelect<T>;
        cta?: T | IntroCtaBlockSelect<T>;
        quote?: T | IntroQuoteBlockSelect<T>;
        separator?: T | IntroSeparatorBlockSelect<T>;
      };
  days?: T;
  abstracts?: T;
  appendices?: T;
  notices?: T;
  city?: T;
  country?: T;
  address?: T;
  longitude?: T;
  latitude?: T;
  location?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  geo?:
    | T
    | {
        summary?: T;
        primaryEntity?: T;
        keyFacts?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  title?: T;
  publishedAt?: T;
  publicArchive?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions_select".
 */
export interface InstitutionsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  country?: T;
  region?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "italian-regions_select".
 */
export interface ItalianRegionsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  _order?: T;
  firstName?: T;
  lastName?: T;
  institution?: T;
  photo?: T;
  bio?: T;
  fullName?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programme-push-subscriptions_select".
 */
export interface ProgrammePushSubscriptionsSelect<T extends boolean = true> {
  endpoint?: T;
  p256dh?: T;
  auth?: T;
  conference?: T;
  canonicalPath?: T;
  items?: T;
  conferenceUpdates?: T;
  notifiedSoon?: T;
  notifiedLive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Institutional footer links, partner logos, credits, and the public Cookie Policy and Privacy Policy pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  structure: {
    /**
     * Optional Lucide icon.
     */
    icon: {
      provider: string;
      name?: string | null;
    };
    label?: string | null;
    /**
     * External site. Opens in a new tab.
     */
    url?: string | null;
  };
  delegation: {
    /**
     * Optional Lucide icon.
     */
    icon: {
      provider: string;
      name?: string | null;
    };
    label?: string | null;
    /**
     * External site. Opens in a new tab.
     */
    url?: string | null;
  };
  /**
   * Upload order is the display order. Media folder “Partner logos”.
   */
  partners?:
    | {
        image: number | Media;
        /**
         * Partner site. Opens in a new tab.
         */
        url?: string | null;
        /**
         * Short description of the logo for screen readers. If empty, the Media Alt Text is used.
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Display order follows this list.
   */
  credits?:
    | {
        role: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  cookiePolicy: {
    /**
     * Page heading and footer link label.
     */
    title: string;
    /**
     * Small label above the title.
     */
    kicker?: string | null;
    /**
     * Badge in the top bar on desktop.
     */
    headerBadge?: string | null;
    /**
     * Shown as “Last updated: …”.
     */
    lastUpdated?: string | null;
    /**
     * Search snippet for this page.
     */
    metaDescription?: string | null;
    /**
     * Lead paragraph under the title.
     */
    intro?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Heading of the highlighted summary box.
     */
    summaryTitle?: string | null;
    summary?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Short points under the summary (e.g. no profiling cookies).
     */
    highlights?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Numbered sections of the cookie statement (use Heading 3).
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  privacyPolicy: {
    /**
     * Page heading and footer link label.
     */
    title: string;
    /**
     * Small label above the title.
     */
    kicker?: string | null;
    /**
     * Badge in the top bar on desktop.
     */
    headerBadge?: string | null;
    /**
     * Shown as “Last updated: …”.
     */
    lastUpdated?: string | null;
    /**
     * Search snippet for this page.
     */
    metaDescription?: string | null;
    /**
     * Lead paragraph under the title.
     */
    intro?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    controllerName?: string | null;
    controllerAddress?: string | null;
    controllerWebsite?: string | null;
    /**
     * Main body after the controller box (use Heading 3 / Heading 4).
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    rightsHeading?: string | null;
    rightsIntro?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    rights?:
      | {
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Closing note on lodging a complaint with the Garante.
     */
    complaintNote?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "active-conference".
 */
export interface ActiveConference {
  id: number;
  /**
   * Published edition on the home page (/). Optional: leave empty for the holding page. That edition is removed from the public archive automatically.
   */
  conference?: (number | null) | Conference;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conference-archive".
 */
export interface ConferenceArchive {
  id: number;
  /**
   * When on, Archive appears in the site menu if at least one edition is listed. When off, the menu item is hidden; /archive and /archive/{slug} stay available.
   */
  enablePublicArchive?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Session reminders for My programme and technical push settings (also used by Notices). Keys stay in environment variables; this screen is for publishers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programme-alerts".
 */
export interface ProgrammeAlert {
  id: number;
  /**
   * If off, the site hides “Enable session alerts” and the minute cron sends nothing.
   */
  enabled?: boolean | null;
  /**
   * Technical contact for Web Push providers (VAPID). Not shown to participants. Required while alerts are on.
   */
  contactEmail?: string | null;
  /**
   * How many minutes before a saved session to notify.
   */
  leadMinutes?: number | null;
  /**
   * Short name on lock-screen notifications.
   */
  notificationTitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  structure?:
    | T
    | {
        icon?:
          | T
          | {
              provider?: T;
              name?: T;
            };
        label?: T;
        url?: T;
      };
  delegation?:
    | T
    | {
        icon?:
          | T
          | {
              provider?: T;
              name?: T;
            };
        label?: T;
        url?: T;
      };
  partners?:
    | T
    | {
        image?: T;
        url?: T;
        alt?: T;
        id?: T;
      };
  credits?:
    | T
    | {
        role?: T;
        name?: T;
        id?: T;
      };
  cookiePolicy?:
    | T
    | {
        title?: T;
        kicker?: T;
        headerBadge?: T;
        lastUpdated?: T;
        metaDescription?: T;
        intro?: T;
        summaryTitle?: T;
        summary?: T;
        highlights?:
          | T
          | {
              label?: T;
              id?: T;
            };
        content?: T;
      };
  privacyPolicy?:
    | T
    | {
        title?: T;
        kicker?: T;
        headerBadge?: T;
        lastUpdated?: T;
        metaDescription?: T;
        intro?: T;
        controllerName?: T;
        controllerAddress?: T;
        controllerWebsite?: T;
        content?: T;
        rightsHeading?: T;
        rightsIntro?: T;
        rights?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        complaintNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "active-conference_select".
 */
export interface ActiveConferenceSelect<T extends boolean = true> {
  conference?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conference-archive_select".
 */
export interface ConferenceArchiveSelect<T extends boolean = true> {
  enablePublicArchive?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programme-alerts_select".
 */
export interface ProgrammeAlertsSelect<T extends boolean = true> {
  enabled?: T;
  contactEmail?: T;
  leadMinutes?: T;
  notificationTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'conferences';
      value: number | Conference;
    } | null;
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}