/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    'abstract-statuses': AbstractStatus;
    abstracts: Abstract;
    appendices: Appendix;
    'agenda-items': AgendaItem;
    'conference-days': ConferenceDay;
    'conference-notices': ConferenceNotice;
    conferences: Conference;
    countries: Country;
    institutions: Institution;
    'italian-regions': ItalianRegion;
    people: Person;
    'programme-push-subscriptions': ProgrammePushSubscription;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    media: {
      abstract: 'abstracts';
      taggedPeople: 'people';
    };
    'agenda-items': {
      children: 'agenda-items';
      childAbstracts: 'abstracts';
    };
    'conference-days': {
      agendaItems: 'agenda-items';
    };
    conferences: {
      days: 'conference-days';
      abstracts: 'abstracts';
      appendices: 'appendices';
      notices: 'conference-notices';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'abstract-statuses': AbstractStatusesSelect<false> | AbstractStatusesSelect<true>;
    abstracts: AbstractsSelect<false> | AbstractsSelect<true>;
    appendices: AppendicesSelect<false> | AppendicesSelect<true>;
    'agenda-items': AgendaItemsSelect<false> | AgendaItemsSelect<true>;
    'conference-days': ConferenceDaysSelect<false> | ConferenceDaysSelect<true>;
    'conference-notices': ConferenceNoticesSelect<false> | ConferenceNoticesSelect<true>;
    conferences: ConferencesSelect<false> | ConferencesSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    institutions: InstitutionsSelect<false> | InstitutionsSelect<true>;
    'italian-regions': ItalianRegionsSelect<false> | ItalianRegionsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    'programme-push-subscriptions': ProgrammePushSubscriptionsSelect<false> | ProgrammePushSubscriptionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    footer: Footer;
    'active-conference': ActiveConference;
    'conference-archive': ConferenceArchive;
    'programme-alerts': ProgrammeAlert;
  };
  globalsSelect: {
    footer: FooterSelect<false> | FooterSelect<true>;
    'active-conference': ActiveConferenceSelect<false> | ActiveConferenceSelect<true>;
    'conference-archive': ConferenceArchiveSelect<false> | ConferenceArchiveSelect<true>;
    'programme-alerts': ProgrammeAlertsSelect<false> | ProgrammeAlertsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Abstract che usano questa immagine. Modificate il collegamento dall’abstract, non da qui.
   */
  abstract?: {
    docs?: (number | Abstract)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Persone la cui foto profilo è questo file. Modificate la foto sulla persona.
   */
  taggedPeople?: {
    docs?: (number | Person)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Abstract scientifici di un’edizione. Meglio crearli e ordinarli dal tab Abstract della conferenza.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abstracts".
 */
export interface Abstract {
  id: number;
  _abstracts_abstracts_order?: string | null;
  _abstracts_childAbstracts_order?: string | null;
  _order?: string | null;
  title: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Codice di ricerca o sessione (es. «CF crio»). Non deve essere unico.
   */
  code?: string | null;
  /**
   * Se selezionato e Content è vuoto, si creano le sezioni predefinite di questo Status.
   */
  status?: (number | null) | AbstractStatus;
  /**
   * Altre coppie Code/Status. Ogni riga aggiunge un’appendice dopo quella principale (stesso ordine).
   */
  relatedCodes?:
    | {
        code?: string | null;
        status?: (number | null) | AbstractStatus;
        id?: string | null;
      }[]
    | null;
  /**
   * Sezioni strutturate. I predefiniti si creano quando selezionate Status e questo elenco è vuoto.
   */
  content?:
    | {
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * La prima riga è l’appendice del Code/Status principale; le successive seguono Related codes. Il numero di righe resta 1 + Related codes.
   */
  appendices?:
    | {
        title?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Autori e relatori in ordine (stesso elenco). Trascinate le righe; assegnate un Role e spuntate Speaker. Ogni persona può comparire una sola volta.
   */
  authors?:
    | {
        person: number | Person;
        role: 'primaryInvestigator' | 'partner' | 'collaborator' | 'teamMember';
        isSpeaker?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Foto ordinate di questo abstract (solo immagini). Sul sito compaiono per prime nel carosello, poi le foto degli Speaker (Team Member esclusi). Cartella Media «Abstract pictures».
   */
  picture?:
    | {
        image: number | Media;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Edizione a cui appartiene questo abstract. Impostata in automatico se lo create dalla conferenza.
   */
  conference: number | Conference;
  /**
   * Sessioni (Agenda items) di questa edizione. Lo stesso abstract può stare sotto più sessioni.
   */
  agendaItems?: (number | AgendaItem)[] | null;
  /**
   * Title in testo semplice ricavato da Title (elenchi).
   */
  plainTitle?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Stati del flusso abstract. Seed; modificare solo se servono etichette o colori diversi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abstract-statuses".
 */
export interface AbstractStatus {
  id: number;
  _order?: string | null;
  /**
   * Chiave dello stato (es. new, ongoing, concluded).
   */
  status: string;
  /**
   * Titoli di sezione copiati sull’abstract quando selezionate questo Status e Content è vuoto. Lasciate vuoto per non copiare nulla.
   */
  defaultContent?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ricercatori, autori, relatori e revisori.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  _order?: string | null;
  firstName: string;
  lastName: string;
  institution?: (number | null) | Institution;
  /**
   * Foto profilo facoltativa. Cartella Media «People photos».
   */
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Generato da First name e Last name.
   */
  fullName?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Istituti di ricerca e laboratori.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions".
 */
export interface Institution {
  id: number;
  _order?: string | null;
  name: string;
  country: number | Country;
  /**
   * Disponibile solo se Country è Italy.
   */
  region?: (number | null) | ItalianRegion;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Paesi del mondo per gli enti. Dati di riferimento (seed).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Regioni italiane per gli indirizzi degli enti. Dati di riferimento (seed).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "italian-regions".
 */
export interface ItalianRegion {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Edizioni della conferenza. Aprite un’edizione per gestire giorni, abstract e appendice.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conferences".
 */
export interface Conference {
  id: number;
  /**
   * Nome formattato della conferenza. Title e slug si ricavano da questo testo.
   */
  name: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Anno dell’edizione. Più edizioni nello stesso anno sono ammesse.
   */
  year: number;
  /**
   * Usato nell’intestazione e come icona della scheda del browser. Cartella Media «Conference logos».
   */
  logo?: (number | null) | Media;
  /**
   * Pulsanti, link e accenti delle sezioni. Si adatta da solo a tema chiaro e scuro.
   */
  primaryColor: string;
  /**
   * Keynote, badge e evidenziazioni secondarie. Si adatta da solo a tema chiaro e scuro.
   */
  secondaryColor: string;
  /**
   * Aggiungete Content (una o più colonne di testo con una Width, come nelle Pages del template Payload), accordion, callout, pulsanti, citazioni e separatori. I blocchi diversi da Content hanno anch’essi una Width. Le larghezze si sommano su una riga a 12 colonne dal breakpoint grande in su (Full = 12, Two thirds = 8, Half = 6, One third = 4) e vanno a capo. Sugli schermi piccoli tutto è a larghezza piena e si impila in ordine.
   */
  intro?:
    | (
        | IntroContentBlock
        | IntroAccordionBlock
        | IntroCalloutBlock
        | IntroCtaBlock
        | IntroQuoteBlock
        | IntroSeparatorBlock
      )[]
    | null;
  /**
   * Ordinati per data (la più vicina per prima). Un giorno per data di calendario.
   */
  days?: {
    docs?: (number | ConferenceDay)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Abstract scientifici di questa edizione. Collegateli alle sessioni dall’abstract o dalla sessione.
   */
  abstracts?: {
    docs?: (number | Abstract)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Al massimo un’appendice per conferenza. Apritela per aggiungere blocchi e trascinarli per l’ordine.
   */
  appendices?: {
    docs?: (number | Appendix)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Avvisi brevi in testo semplice. Trascinate per l’ordine del banner. Create un nuovo avviso per ogni push: non si può reinviare.
   */
  notices?: {
    docs?: (number | ConferenceNotice)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  city: string;
  country: string;
  address: string;
  /**
   * Coordinata X (es. 13.8046 per Trieste).
   */
  longitude?: number | null;
  /**
   * Coordinata Y (es. 45.6495 per Trieste).
   */
  latitude?: number | null;
  /**
   * Dettagli facoltativi (sala, ingresso, accessibilità).
   */
  location?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Questo blocco è la scheda breve che le persone vedono prima di aprire la pagina: il titolo blu su Google, l’anteprima su WhatsApp o LinkedIn, e il testo nella scheda del browser. Non è il contenuto della pagina (quello sta in Name, Intro e Venue).
   */
  meta?: {
    /**
     * Il titolo che Google e motori simili mostrano di solito. Scrivi il nome dell’edizione come la cercherebbe una persona, con l’anno se serve (esempio: «FCR 2026 — Trieste»). Resta sotto i 60 caratteri circa, così non viene tagliato. Usa Generate per copiare il nome della conferenza, poi accorcialo se serve. Se lo lasci vuoto, la pagina pubblica usa il nome della conferenza più «FCR».
     */
    title?: string | null;
    /**
     * L’immagine che compare quando qualcuno condivide il link di questa edizione (WhatsApp, Slack, LinkedIn, email). Meglio una foto orizzontale ampia della sede, del manifesto o del logo su sfondo semplice. Punta a meno di 500 KB; il limite di caricamento è 12 MB. Un’immagine 1200×630 px riempie l’anteprima senza tagliare il soggetto. Se la lasci vuota, il sito usa l’immagine di condivisione predefinita FCR.
     */
    image?: (number | null) | Media;
    /**
     * Due frasi (circa 150–160 caratteri) che compaiono sotto il titolo su Google e nell’anteprima di condivisione. Di’ che edizione è, dove si svolge e a chi è rivolta. Esempio: «FCR 2026 è un incontro di medicina rigenerativa a Trieste per clinici e ricercatori. Date, sede e programma.» Non inserire elenchi di parole chiave. Se lo lasci vuoto, i motori di ricerca ricostruiranno il testo dalla pagina.
     */
    description?: string | null;
  };
  /**
   * Facoltativo. ChatGPT, Gemini, Perplexity e strumenti simili citano spesso fatti brevi e stabili, non i testi lunghi della pagina. Compila questi campi perché possano nominare l’edizione in modo corretto. Non vengono mostrati come FAQ sul sito. Date, città, indirizzo e coordinate si prendono da Days e Venue: non ripeterli qui, salvo che ti serva una formulazione precisa in una riga.
   */
  geo?: {
    /**
     * Una o due frasi di fatto che un assistente può citare. Inizia con il nome ufficiale, poi luogo, destinatari e tema. Esempio: «FCR 2026 è l’incontro annuale FCR di medicina rigenerativa, a Trieste, per clinici e ricercatori.» Evita slogan («il convegno migliore di sempre»). Se è vuoto, gli assistenti usano il testo breve sopra, poi il contenuto della pagina.
     */
    summary?: string | null;
    /**
     * Il nome esatto che vuoi sia citato come soggetto della pagina, per non confonderla con un altro anno o un altro evento FCR. Esempio: «FCR 2026» o «Fondazione conferenza 2026, Trieste». Tienilo breve. Se è vuoto, si usa il nome della conferenza.
     */
    primaryEntity?: string | null;
    /**
     * Coppie brevi etichetta–valore da citare così come sono. Usale per ciò che è facile sbagliare (tema, destinatari, lingua, organizzato da). Non duplicare città, indirizzo o date, salvo che serva una frase precisa. Esempi: Tema → Medicina rigenerativa; Destinatari → Clinici e ricercatori; Lingua → Inglese. Bastano quattro-otto fatti.
     */
    keyFacts?:
      | {
          /**
           * Il tipo di fatto, in una o due parole. Esempi: Tema, Destinatari, Lingua, Organizzato da.
           */
          label?: string | null;
          /**
           * Il fatto, come lo diresti a un collega. Una sola riga. Esempio: «Clinici e ricercatori accademici».
           */
          value?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Title in testo semplice ricavato da Name (elenchi, slug e scheda pubblica).
   */
  title?: string | null;
  /**
   * Prima messa online di questa edizione. Resta stabile per la SEO; non sono le date dell’evento (quelle stanno in Days).
   */
  publishedAt?: string | null;
  publicArchive?: boolean | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroContentBlock".
 */
export interface IntroContentBlock {
  /**
   * Le Width si sommano su una riga a 12 colonne dal breakpoint grande in su (Full = 12, Two thirds = 8, Half = 6, One third = 4) e vanno a capo. Sugli schermi piccoli ogni colonna è a larghezza piena.
   */
  columns?:
    | {
        size: 'full' | 'twoThirds' | 'half' | 'oneThird';
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroAccordionBlock".
 */
export interface IntroAccordionBlock {
  size: 'full' | 'twoThirds' | 'half' | 'oneThird';
  items?:
    | {
        title: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        defaultOpen?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroCalloutBlock".
 */
export interface IntroCalloutBlock {
  size: 'full' | 'twoThirds' | 'half' | 'oneThird';
  /**
   * Usate Deadline per date e scadenze, Important per avvisi da leggere.
   */
  tone: 'note' | 'important' | 'deadline';
  title?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroCtaBlock".
 */
export interface IntroCtaBlock {
  size: 'full' | 'twoThirds' | 'half' | 'oneThird';
  label: string;
  destination: 'programme' | 'venue' | 'appendix' | 'custom';
  /**
   * Sito esterno, o un percorso di pagina come /archive/…
   */
  url?: string | null;
  newTab?: boolean | null;
  appearance: 'solid' | 'outline';
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroQuoteBlock".
 */
export interface IntroQuoteBlock {
  size: 'full' | 'twoThirds' | 'half' | 'oneThird';
  quote: string;
  /**
   * Relatore, ruolo o fonte, facoltativo.
   */
  attribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroSeparatorBlock".
 */
export interface IntroSeparatorBlock {
  size: 'full' | 'twoThirds' | 'half' | 'oneThird';
  style: 'line' | 'space';
  id?: string | null;
  blockName?: string | null;
  blockType: 'separator';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conference-days".
 */
export interface ConferenceDay {
  id: number;
  date: string;
  startTime: string;
  /**
   * Può essere prima di Start time se il giorno passa la mezzanotte.
   */
  endTime: string;
  /**
   * Sessioni di primo livello di questo giorno. Le voci nidificate si gestiscono sul genitore. Trascinate per riordinare.
   */
  agendaItems?: {
    docs?: (number | AgendaItem)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Conferenza di appartenenza. Impostata in automatico se create il giorno dalla conferenza.
   */
  conference: number | Conference;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agenda-items".
 */
export interface AgendaItem {
  id: number;
  '_agenda-items_agendaItems_order'?: string | null;
  '_agenda-items_children_order'?: string | null;
  _order?: string | null;
  /**
   * Titolo formattato della sessione. Title in testo semplice si ricava da questo.
   */
  name: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Selezionate prima il giorno. Start time e End time restano nei limiti orari di quel giorno.
   */
  day: number | ConferenceDay;
  startTime?: string | null;
  endTime?: string | null;
  /**
   * Evidenzia graficamente questa sessione sul sito.
   */
  isKeynote?: boolean | null;
  durationMinutes?: number | null;
  /**
   * Icona Lucide facoltativa. La ricerca filtra l’elenco; scorrete per vederle tutte.
   */
  icon: {
    provider: string;
    name?: string | null;
  };
  /**
   * Note o dettagli facoltativi sulla sessione.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Interventi o sotto-sessioni. Trascinate per l’ordine dentro questa voce.
   */
  children?: {
    docs?: (number | AgendaItem)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Abstract scientifici sotto questa sessione. Lo stesso abstract può comparire anche in altre voci.
   */
  childAbstracts?: {
    docs?: (number | Abstract)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Title in testo semplice ricavato da Title (elenchi).
   */
  title?: string | null;
  /**
   * Voce genitore facoltativa (stesso giorno). Lasciate vuoto per le sessioni di primo livello.
   */
  parent?: (number | null) | AgendaItem;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Un’appendice per edizione. Aggiungete blocchi ordinati (testo, elenco enti, …) e trascinateli per l’ordine.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appendices".
 */
export interface Appendix {
  id: number;
  /**
   * Ogni blocco ha un Title obbligatorio (etichetta della linguetta). Basic text usa le stesse colonne Content, accordion e layout dell’intro. Trascinate per riordinare le linguette.
   */
  blocks: (
    BasicTextAppendixBlock | ReviewersAppendixBlock | ResearchProjectsAppendixBlock | InstitutionsAppendixBlock
  )[];
  /**
   * Edizione a cui appartiene questa appendice. Ogni conferenza può averne una sola.
   */
  conference: number | Conference;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BasicTextAppendixBlock".
 */
export interface BasicTextAppendixBlock {
  /**
   * Etichetta della linguetta nell’appendice pubblica.
   */
  title: string;
  /**
   * Shown next to the tab title. If empty, a default icon for this block type is used.
   */
  icon: {
    provider: string;
    name?: string | null;
  };
  /**
   * Aggiungete Content (una o più colonne di testo con una Width, come nelle Pages del template Payload), accordion, callout, pulsanti, citazioni e separatori. I blocchi diversi da Content hanno anch’essi una Width. Le larghezze si sommano su una riga a 12 colonne dal breakpoint grande in su (Full = 12, Two thirds = 8, Half = 6, One third = 4) e vanno a capo. Sugli schermi piccoli tutto è a larghezza piena e si impila in ordine.
   */
  layout?:
    | (
        | IntroContentBlock
        | IntroAccordionBlock
        | IntroCalloutBlock
        | IntroCtaBlock
        | IntroQuoteBlock
        | IntroSeparatorBlock
      )[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'basicText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewersAppendixBlock".
 */
export interface ReviewersAppendixBlock {
  title: string;
  /**
   * Shown next to the tab title. If empty, a default icon for this block type is used.
   */
  icon: {
    provider: string;
    name?: string | null;
  };
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'reviewers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResearchProjectsAppendixBlock".
 */
export interface ResearchProjectsAppendixBlock {
  title: string;
  /**
   * Shown next to the tab title. If empty, a default icon for this block type is used.
   */
  icon: {
    provider: string;
    name?: string | null;
  };
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'researchProjects';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InstitutionsAppendixBlock".
 */
export interface InstitutionsAppendixBlock {
  title: string;
  /**
   * Shown next to the tab title. If empty, a default icon for this block type is used.
   */
  icon: {
    provider: string;
    name?: string | null;
  };
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * All institutions except those of non–team-member authors on this conference’s abstracts. Create new ones here if needed. Drag to set display order.
   */
  institutions?: (number | Institution)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'institutions';
}
/**
 * Cambiamenti in diretta sul programma. Si modificano dal tab Avvisi della conferenza. Usate Invia push per le notifiche a schermo bloccato.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conference-notices".
 */
export interface ConferenceNotice {
  id: number;
  '_conference-notices_notices_order'?: string | null;
  _order?: string | null;
  /**
   * Titolo breve per banner e schermo bloccato (max 40 caratteri).
   */
  title: string;
  /**
   * Solo testo (max 120 caratteri). Compare sul banner del sito e nella push.
   */
  body: string;
  /**
   * Colore del banner. Preferite Change per cambi di sala o orario.
   */
  severity: 'info' | 'change' | 'urgent';
  /**
   * Se è acceso, i visitatori vedono l’avviso sulla pagina pubblica dell’edizione.
   */
  showOnSite?: boolean | null;
  /**
   * Se è acceso, Invia push recapita una notifica a schermo bloccato ai dispositivi iscritti di questa edizione.
   */
  sendPush?: boolean | null;
  /**
   * Facoltativo. La push arriva solo a chi ha salvato questa sessione (più chi è iscritto agli aggiornamenti della conferenza). Il banner resta visibile a tutti.
   */
  relatedAgendaItem?: (number | null) | AgendaItem;
  /**
   * Percorso facoltativo su questo sito, es. #programme o ?agenda=123. Vuoto apre la home dell’edizione (o la sessione collegata, se impostata).
   */
  linkPath?: string | null;
  /**
   * Facoltativo. Banner nascosto prima di questo orario.
   */
  startsAt?: string | null;
  /**
   * Facoltativo. Banner nascosto dopo questo orario.
   */
  expiresAt?: string | null;
  /**
   * Compilato in automatico dopo un invio push riuscito.
   */
  sentAt?: string | null;
  /**
   * Dispositivi che hanno ricevuto l’ultimo invio.
   */
  pushSent?: number | null;
  /**
   * Endpoint push scaduti o assenti, puliti all’ultimo invio.
   */
  pushRemoved?: number | null;
  /**
   * Edizione a cui appartiene questo avviso.
   */
  conference: number | Conference;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Endpoint push del browser per gli avvisi di My programme. Non si modificano da qui.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programme-push-subscriptions".
 */
export interface ProgrammePushSubscription {
  id: number;
  endpoint: string;
  p256dh: string;
  auth: string;
  conference: number;
  canonicalPath?: string | null;
  items:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Se è vero, questo endpoint riceve anche gli avvisi editoriali (sala/orario), non solo i promemoria di sessione.
   */
  conferenceUpdates?: boolean | null;
  notifiedSoon?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notifiedLive?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'abstract-statuses';
        value: number | AbstractStatus;
      } | null)
    | ({
        relationTo: 'abstracts';
        value: number | Abstract;
      } | null)
    | ({
        relationTo: 'appendices';
        value: number | Appendix;
      } | null)
    | ({
        relationTo: 'agenda-items';
        value: number | AgendaItem;
      } | null)
    | ({
        relationTo: 'conference-days';
        value: number | ConferenceDay;
      } | null)
    | ({
        relationTo: 'conference-notices';
        value: number | ConferenceNotice;
      } | null)
    | ({
        relationTo: 'conferences';
        value: number | Conference;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'institutions';
        value: number | Institution;
      } | null)
    | ({
        relationTo: 'italian-regions';
        value: number | ItalianRegion;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'programme-push-subscriptions';
        value: number | ProgrammePushSubscription;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  abstract?: T;
  taggedPeople?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abstract-statuses_select".
 */
export interface AbstractStatusesSelect<T extends boolean = true> {
  _order?: T;
  status?: T;
  defaultContent?:
    | T
    | {
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "abstracts_select".
 */
export interface AbstractsSelect<T extends boolean = true> {
  _abstracts_abstracts_order?: T;
  _abstracts_childAbstracts_order?: T;
  _order?: T;
  title?: T;
  code?: T;
  status?: T;
  relatedCodes?:
    | T
    | {
        code?: T;
        status?: T;
        id?: T;
      };
  content?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  appendices?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  authors?:
    | T
    | {
        person?: T;
        role?: T;
        isSpeaker?: T;
        id?: T;
      };
  picture?:
    | T
    | {
        image?: T;
        description?: T;
        id?: T;
      };
  conference?: T;
  agendaItems?: T;
  plainTitle?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appendices_select".
 */
export interface AppendicesSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        basicText?: T | BasicTextAppendixBlockSelect<T>;
        reviewers?: T | ReviewersAppendixBlockSelect<T>;
        researchProjects?: T | ResearchProjectsAppendixBlockSelect<T>;
        institutions?: T | InstitutionsAppendixBlockSelect<T>;
      };
  conference?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BasicTextAppendixBlock_select".
 */
export interface BasicTextAppendixBlockSelect<T extends boolean = true> {
  title?: T;
  icon?:
    | T
    | {
        provider?: T;
        name?: T;
      };
  layout?:
    | T
    | {
        content?: T | IntroContentBlockSelect<T>;
        accordion?: T | IntroAccordionBlockSelect<T>;
        callout?: T | IntroCalloutBlockSelect<T>;
        cta?: T | IntroCtaBlockSelect<T>;
        quote?: T | IntroQuoteBlockSelect<T>;
        separator?: T | IntroSeparatorBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroContentBlock_select".
 */
export interface IntroContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        content?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroAccordionBlock_select".
 */
export interface IntroAccordionBlockSelect<T extends boolean = true> {
  size?: T;
  items?:
    | T
    | {
        title?: T;
        content?: T;
        defaultOpen?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroCalloutBlock_select".
 */
export interface IntroCalloutBlockSelect<T extends boolean = true> {
  size?: T;
  tone?: T;
  title?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroCtaBlock_select".
 */
export interface IntroCtaBlockSelect<T extends boolean = true> {
  size?: T;
  label?: T;
  destination?: T;
  url?: T;
  newTab?: T;
  appearance?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroQuoteBlock_select".
 */
export interface IntroQuoteBlockSelect<T extends boolean = true> {
  size?: T;
  quote?: T;
  attribution?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IntroSeparatorBlock_select".
 */
export interface IntroSeparatorBlockSelect<T extends boolean = true> {
  size?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewersAppendixBlock_select".
 */
export interface ReviewersAppendixBlockSelect<T extends boolean = true> {
  title?: T;
  icon?:
    | T
    | {
        provider?: T;
        name?: T;
      };
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResearchProjectsAppendixBlock_select".
 */
export interface ResearchProjectsAppendixBlockSelect<T extends boolean = true> {
  title?: T;
  icon?:
    | T
    | {
        provider?: T;
        name?: T;
      };
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InstitutionsAppendixBlock_select".
 */
export interface InstitutionsAppendixBlockSelect<T extends boolean = true> {
  title?: T;
  icon?:
    | T
    | {
        provider?: T;
        name?: T;
      };
  description?: T;
  institutions?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agenda-items_select".
 */
export interface AgendaItemsSelect<T extends boolean = true> {
  '_agenda-items_agendaItems_order'?: T;
  '_agenda-items_children_order'?: T;
  _order?: T;
  name?: T;
  day?: T;
  startTime?: T;
  endTime?: T;
  isKeynote?: T;
  durationMinutes?: T;
  icon?:
    | T
    | {
        provider?: T;
        name?: T;
      };
  description?: T;
  children?: T;
  childAbstracts?: T;
  title?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conference-days_select".
 */
export interface ConferenceDaysSelect<T extends boolean = true> {
  date?: T;
  startTime?: T;
  endTime?: T;
  agendaItems?: T;
  conference?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conference-notices_select".
 */
export interface ConferenceNoticesSelect<T extends boolean = true> {
  '_conference-notices_notices_order'?: T;
  _order?: T;
  title?: T;
  body?: T;
  severity?: T;
  showOnSite?: T;
  sendPush?: T;
  relatedAgendaItem?: T;
  linkPath?: T;
  startsAt?: T;
  expiresAt?: T;
  sentAt?: T;
  pushSent?: T;
  pushRemoved?: T;
  conference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conferences_select".
 */
export interface ConferencesSelect<T extends boolean = true> {
  name?: T;
  year?: T;
  logo?: T;
  primaryColor?: T;
  secondaryColor?: T;
  intro?:
    | T
    | {
        content?: T | IntroContentBlockSelect<T>;
        accordion?: T | IntroAccordionBlockSelect<T>;
        callout?: T | IntroCalloutBlockSelect<T>;
        cta?: T | IntroCtaBlockSelect<T>;
        quote?: T | IntroQuoteBlockSelect<T>;
        separator?: T | IntroSeparatorBlockSelect<T>;
      };
  days?: T;
  abstracts?: T;
  appendices?: T;
  notices?: T;
  city?: T;
  country?: T;
  address?: T;
  longitude?: T;
  latitude?: T;
  location?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  geo?:
    | T
    | {
        summary?: T;
        primaryEntity?: T;
        keyFacts?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  title?: T;
  publishedAt?: T;
  publicArchive?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions_select".
 */
export interface InstitutionsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  country?: T;
  region?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "italian-regions_select".
 */
export interface ItalianRegionsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  _order?: T;
  firstName?: T;
  lastName?: T;
  institution?: T;
  photo?: T;
  bio?: T;
  fullName?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programme-push-subscriptions_select".
 */
export interface ProgrammePushSubscriptionsSelect<T extends boolean = true> {
  endpoint?: T;
  p256dh?: T;
  auth?: T;
  conference?: T;
  canonicalPath?: T;
  items?: T;
  conferenceUpdates?: T;
  notifiedSoon?: T;
  notifiedLive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  structure: {
    /**
     * Icona Lucide facoltativa.
     */
    icon: {
      provider: string;
      name?: string | null;
    };
    label?: string | null;
    /**
     * Sito esterno. Si apre in una nuova scheda.
     */
    url?: string | null;
  };
  delegation: {
    /**
     * Icona Lucide facoltativa.
     */
    icon: {
      provider: string;
      name?: string | null;
    };
    label?: string | null;
    /**
     * Sito esterno. Si apre in una nuova scheda.
     */
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "active-conference".
 */
export interface ActiveConference {
  id: number;
  /**
   * Edizione pubblicata in home (/). Obbligatoria. Quell’edizione viene tolta automaticamente dall’archivio pubblico.
   */
  conference: number | Conference;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conference-archive".
 */
export interface ConferenceArchive {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Promemoria delle sessioni per My programme e impostazioni tecniche della push (usate anche dagli avvisi in Notices). Le chiavi restano nelle variabili d’ambiente; questa schermata è per chi pubblica.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programme-alerts".
 */
export interface ProgrammeAlert {
  id: number;
  /**
   * Se è spento, il sito nasconde “Enable session alerts” e il cron al minuto non invia nulla.
   */
  enabled?: boolean | null;
  /**
   * Contatto tecnico per i provider Web Push (VAPID). Non visibile ai partecipanti. Obbligatorio mentre gli avvisi sono accesi.
   */
  contactEmail?: string | null;
  /**
   * Avvisare tanti minuti prima di una sessione salvata.
   */
  leadMinutes?: number | null;
  /**
   * Nome breve sulle notifiche a schermo bloccato.
   */
  notificationTitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  structure?:
    | T
    | {
        icon?:
          | T
          | {
              provider?: T;
              name?: T;
            };
        label?: T;
        url?: T;
      };
  delegation?:
    | T
    | {
        icon?:
          | T
          | {
              provider?: T;
              name?: T;
            };
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "active-conference_select".
 */
export interface ActiveConferenceSelect<T extends boolean = true> {
  conference?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conference-archive_select".
 */
export interface ConferenceArchiveSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programme-alerts_select".
 */
export interface ProgrammeAlertsSelect<T extends boolean = true> {
  enabled?: T;
  contactEmail?: T;
  leadMinutes?: T;
  notificationTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'conferences';
      value: number | Conference;
    } | null;
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}